#!/bin/sh
ROOT=$(dirname "$0")
ROOT=$(dirname "$ROOT")
ROOT=$(dirname "$ROOT")
echo "php-cs-fixer pre commit hook start"
PHP_CS_FIXER="tools/php-cs-fixer/vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false
if [ -x  "$PHP_CS_FIXER" ]; then
    HAS_PHP_CS_FIXER=true
else
    echo "PHP CS Fixer not installed into $PHP_CS_FIXER"
fi
PHP_CS_CONFIG=.php-cs-fixer.dist.php
if [ "x$PHP_CS_CONFIG" = "x" ]; then
    echo "No PHP CS Fixer config file found !"
    HAS_PHP_CS_FIXER=false
fi
if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS_FIXER fix --config=$ROOT/$PHP_CS_CONFIG --verbose "$line";
        git add "$line";
    done
else
    echo ""
    echo "Please install php-cs-fixer, see README.md"
fi
echo "php-cs-fixer pre commit hook finish"